const Movies = [
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BNjEzYjJmNzgtNDkwNy00MTQ4LTlmMWMtNzA4YjE2NjI0ZDg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Apollo 13",
    Released_Year: "PG",
    Certificate: "U",
    Runtime: "140 min",
    Genre: "Adventure, Drama, History",
    IMDB_Rating: 7.6,
    Overview:
      "NASA must devise a strategy to return Apollo 13 to Earth safely after the spacecraft undergoes massive internal damage putting the lives of the three astronauts on board in jeopardy.",
    Meta_score: 77,
    Director: "Ron Howard",
    Star1: "Tom Hanks",
    Star2: "Bill Paxton",
    Star3: "Kevin Bacon",
    Star4: "Gary Sinise",
    No_of_Votes: 269197,
    Gross: "17,38,37,933",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BNjViNWRjYWEtZTI0NC00N2E3LTk0NGQtMjY4NTM3OGNkZjY0XkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Hamilton",
    Released_Year: 2020,
    Certificate: "PG-13",
    Runtime: "160 min",
    Genre: "Biography, Drama, History",
    IMDB_Rating: 8.6,
    Overview:
      "The real life of one of America's foremost founding fathers and first Secretary of the Treasury, Alexander Hamilton. Captured live on Broadway from the Richard Rodgers Theater with the original Broadway cast.",
    Meta_score: 90,
    Director: "Thomas Kail",
    Star1: "Lin-Manuel Miranda",
    Star2: "Phillipa Soo",
    Star3: "Leslie Odom Jr.",
    Star4: "Renée Elise Goldsberry",
    No_of_Votes: 55291,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BOTc2ZTlmYmItMDBhYS00YmMzLWI4ZjAtMTI5YTBjOTFiMGEwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY98_CR0,0,67,98_AL_.jpg",
    Series_Title: "Soorarai Pottru",
    Released_Year: 2020,
    Certificate: "U",
    Runtime: "153 min",
    Genre: "Drama",
    IMDB_Rating: 8.6,
    Overview:
      'Nedumaaran Rajangam "Maara" sets out to make the common man fly and in the process takes on the world\'s most capital intensive industry and several enemies who stand in his way.',
    Meta_score: "",
    Director: "Sudha Kongara",
    Star1: "Suriya",
    Star2: "Madhavan",
    Star3: "Paresh Rawal",
    Star4: "Aparna Balamurali",
    No_of_Votes: 54995,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BZGE1MDg5M2MtNTkyZS00MTY5LTg1YzUtZTlhZmM1Y2EwNmFmXkEyXkFqcGdeQXVyNjA3OTI0MDc@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Soul",
    Released_Year: 2020,
    Certificate: "U",
    Runtime: "100 min",
    Genre: "Animation, Adventure, Comedy",
    IMDB_Rating: 8.1,
    Overview:
      "After landing the gig of a lifetime, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife.",
    Meta_score: 83,
    Director: "Pete Docter",
    Star1: "Kemp Powers",
    Star2: "Jamie Foxx",
    Star3: "Tina Fey",
    Star4: "Graham Norton",
    No_of_Votes: 159171,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BNmI0MTliMTAtMmJhNC00NTJmLTllMzQtMDI3NzA1ODMyZWI1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY98_CR5,0,67,98_AL_.jpg",
    Series_Title: "Dil Bechara",
    Released_Year: 2020,
    Certificate: "UA",
    Runtime: "101 min",
    Genre: "Comedy, Drama, Romance",
    IMDB_Rating: 7.9,
    Overview:
      "The emotional journey of two hopelessly in love youngsters, a young girl, Kizie, suffering from cancer, and a boy, Manny, whom she meets at a support group.",
    Meta_score: "",
    Director: "Mukesh Chhabra",
    Star1: "Sushant Singh Rajput",
    Star2: "Sanjana Sanghi",
    Star3: "Sahil Vaid",
    Star4: "Saswata Chatterjee",
    No_of_Votes: 111478,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BYjYzOGE1MjUtODgyMy00ZDAxLTljYTgtNzk0Njg2YWQwMTZhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "The Trial of the Chicago 7",
    Released_Year: 2020,
    Certificate: "R",
    Runtime: "129 min",
    Genre: "Drama, History, Thriller",
    IMDB_Rating: 7.8,
    Overview:
      "The story of 7 people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention in Chicago, Illinois.",
    Meta_score: 77,
    Director: "Aaron Sorkin",
    Star1: "Eddie Redmayne",
    Star2: "Alex Sharp",
    Star3: "Sacha Baron Cohen",
    Star4: "Jeremy Strong",
    No_of_Votes: 89896,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BOTNjM2Y2ZjgtMDc5NS00MDQ1LTgyNGYtYzYwMTAyNWQwYTMyXkEyXkFqcGdeQXVyMjE4NzUxNDA@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Druk",
    Released_Year: 2020,
    Certificate: "",
    Runtime: "117 min",
    Genre: "Comedy, Drama",
    IMDB_Rating: 7.8,
    Overview:
      "Four friends, all high school teachers, test a theory that they will improve their lives by maintaining a constant level of alcohol in their blood.",
    Meta_score: 81,
    Director: "Thomas Vinterberg",
    Star1: "Mads Mikkelsen",
    Star2: "Thomas Bo Larsen",
    Star3: "Magnus Millang",
    Star4: "Lars Ranthe",
    No_of_Votes: 33931,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Gisaengchung",
    Released_Year: 2019,
    Certificate: "A",
    Runtime: "132 min",
    Genre: "Comedy, Drama, Thriller",
    IMDB_Rating: 8.6,
    Overview:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    Meta_score: 96,
    Director: "Bong Joon Ho",
    Star1: "Kang-ho Song",
    Star2: "Lee Sun-kyun",
    Star3: "Cho Yeo-jeong",
    Star4: "Choi Woo-sik",
    No_of_Votes: 552778,
    Gross: "5,33,67,844",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Joker",
    Released_Year: 2019,
    Certificate: "A",
    Runtime: "122 min",
    Genre: "Crime, Drama, Thriller",
    IMDB_Rating: 8.5,
    Overview:
      "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    Meta_score: 59,
    Director: "Todd Phillips",
    Star1: "Joaquin Phoenix",
    Star2: "Robert De Niro",
    Star3: "Zazie Beetz",
    Star4: "Frances Conroy",
    No_of_Votes: 939252,
    Gross: "33,54,51,311",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Avengers: Endgame",
    Released_Year: 2019,
    Certificate: "UA",
    Runtime: "181 min",
    Genre: "Action, Adventure, Drama",
    IMDB_Rating: 8.4,
    Overview:
      "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    Meta_score: 78,
    Director: "Anthony Russo",
    Star1: "Joe Russo",
    Star2: "Robert Downey Jr.",
    Star3: "Chris Evans",
    Star4: "Mark Ruffalo",
    No_of_Votes: 809955,
    Gross: "85,83,73,000",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: 1917,
    Released_Year: 2019,
    Certificate: "R",
    Runtime: "119 min",
    Genre: "Drama, Thriller, War",
    IMDB_Rating: 8.3,
    Overview:
      "April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.",
    Meta_score: 78,
    Director: "Sam Mendes",
    Star1: "Dean-Charles Chapman",
    Star2: "George MacKay",
    Star3: "Daniel Mays",
    Star4: "Colin Firth",
    No_of_Votes: 425844,
    Gross: "15,92,27,644",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BOGE3N2QxN2YtM2ZlNS00MWIyLWE1NDAtYWFlN2FiYjY1MjczXkEyXkFqcGdeQXVyOTUwNzc0ODc@._V1_UY98_CR1,0,67,98_AL_.jpg",
    Series_Title: "Miracle in cell NO.7",
    Released_Year: 2019,
    Certificate: "TV-14",
    Runtime: "132 min",
    Genre: "Drama",
    IMDB_Rating: 8.3,
    Overview:
      "A story of love between a mentally-ill father who was wrongly accused of murder and his lovely six years old daughter. The prison would be their home. Based on the 2013 Korean movie 7-beon-bang-ui seon-mul (2013).",
    Meta_score: "",
    Director: "Mehmet Ada Öztekin",
    Star1: "Aras Bulut Iynemli",
    Star2: "Nisa Sofiya Aksongur",
    Star3: "Deniz Baysal",
    Star4: "Celile Toyon Uysal",
    No_of_Votes: 33935,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BYjg2ZDI2YTYtN2EwYi00YWI5LTgyMWQtMWFkYmE3NmJkOGVhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY98_CR0,0,67,98_AL_.jpg",
    Series_Title: "Chhichhore",
    Released_Year: 2019,
    Certificate: "UA",
    Runtime: "143 min",
    Genre: "Comedy, Drama",
    IMDB_Rating: 8.2,
    Overview:
      "A tragic incident forces Anirudh, a middle-aged man, to take a trip down memory lane and reminisce his college days along with his friends, who were labelled as losers.",
    Meta_score: "",
    Director: "Nitesh Tiwari",
    Star1: "Sushant Singh Rajput",
    Star2: "Shraddha Kapoor",
    Star3: "Varun Sharma",
    Star4: "Prateik",
    No_of_Votes: 33893,
    Gross: "8,98,575",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BMWYwOThjM2ItZGYxNy00NTQwLWFlZWEtM2MzM2Q5MmY3NDU5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Klaus",
    Released_Year: 2019,
    Certificate: "PG",
    Runtime: "96 min",
    Genre: "Animation, Adventure, Comedy",
    IMDB_Rating: 8.2,
    Overview:
      "A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.",
    Meta_score: 65,
    Director: "Sergio Pablos",
    Star1: "Carlos Martínez López",
    Star2: "Jason Schwartzman",
    Star3: "J.K. Simmons",
    Star4: "Rashida Jones",
    No_of_Votes: 104761,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BNjgwNjkwOWYtYmM3My00NzI1LTk5OGItYWY0OTMyZTY4OTg2XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Portrait de la jeune fille en feu",
    Released_Year: 2019,
    Certificate: "R",
    Runtime: "122 min",
    Genre: "Drama, Romance",
    IMDB_Rating: 8.1,
    Overview:
      "On an isolated island in Brittany at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.",
    Meta_score: 95,
    Director: "Céline Sciamma",
    Star1: "Noémie Merlant",
    Star2: "Adèle Haenel",
    Star3: "Luàna Bajrami",
    Star4: "Valeria Golino",
    No_of_Votes: 63134,
    Gross: "37,59,854",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BM2UwMDVmMDItM2I2Yi00NGZmLTk4ZTUtY2JjNTQ3OGQ5ZjM2XkEyXkFqcGdeQXVyMTA1OTYzOTUx._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Ford v Ferrari",
    Released_Year: 2019,
    Certificate: "UA",
    Runtime: "152 min",
    Genre: "Action, Biography, Drama",
    IMDB_Rating: 8.1,
    Overview:
      "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.",
    Meta_score: 81,
    Director: "James Mangold",
    Star1: "Matt Damon",
    Star2: "Christian Bale",
    Star3: "Jon Bernthal",
    Star4: "Caitriona Balfe",
    No_of_Votes: 291289,
    Gross: "11,76,24,028",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BNjJkYTc5N2UtMGRlMC00M2FmLTk0ZWMtOTYxNDUwNjI2YzljXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Togo",
    Released_Year: 2019,
    Certificate: "U",
    Runtime: "113 min",
    Genre: "Adventure, Biography, Drama",
    IMDB_Rating: 8,
    Overview:
      "The story of Togo, the sled dog who led the 1925 serum run yet was considered by most to be too small and weak to lead such an intense race.",
    Meta_score: 69,
    Director: "Ericson Core",
    Star1: "Willem Dafoe",
    Star2: "Julianne Nicholson",
    Star3: "Christopher Heyerdahl",
    Star4: "Richard Dormer",
    No_of_Votes: 37556,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BZDkzMTQ1YTMtMWY4Ny00MzExLTkzYzEtNzZhOTczNzU2NTU1XkEyXkFqcGdeQXVyODY3NjMyMDU@._V1_UY98_CR4,0,67,98_AL_.jpg",
    Series_Title: "Gully Boy",
    Released_Year: 2019,
    Certificate: "UA",
    Runtime: "154 min",
    Genre: "Drama, Music, Romance",
    IMDB_Rating: 8,
    Overview:
      "A coming-of-age story based on the lives of street rappers in Mumbai.",
    Meta_score: 65,
    Director: "Zoya Akhtar",
    Star1: "Vijay Varma",
    Star2: "Nakul Roshan Sahdev",
    Star3: "Ranveer Singh",
    Star4: "Vijay Raaz",
    No_of_Votes: 31886,
    Gross: "55,66,534",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Knives Out",
    Released_Year: 2019,
    Certificate: "UA",
    Runtime: "130 min",
    Genre: "Comedy, Crime, Drama",
    IMDB_Rating: 7.9,
    Overview:
      "A detective investigates the death of a patriarch of an eccentric, combative family.",
    Meta_score: 82,
    Director: "Rian Johnson",
    Star1: "Daniel Craig",
    Star2: "Chris Evans",
    Star3: "Ana de Armas",
    Star4: "Jamie Lee Curtis",
    No_of_Votes: 454203,
    Gross: "16,53,59,751",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BZGVmY2RjNDgtMTc3Yy00YmY0LTgwODItYzBjNWJhNTRlYjdkXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Marriage Story",
    Released_Year: 2019,
    Certificate: "U",
    Runtime: "137 min",
    Genre: "Comedy, Drama, Romance",
    IMDB_Rating: 7.9,
    Overview:
      "Noah Baumbach's incisive and compassionate look at a marriage breaking up and a family staying together.",
    Meta_score: 94,
    Director: "Noah Baumbach",
    Star1: "Adam Driver",
    Star2: "Scarlett Johansson",
    Star3: "Julia Greer",
    Star4: "Azhy Robertson",
    No_of_Votes: 246644,
    Gross: "20,00,000",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BZjU0Yzk2MzEtMjAzYy00MzY0LTg2YmItM2RkNzdkY2ZhN2JkXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Jojo Rabbit",
    Released_Year: 2019,
    Certificate: "UA",
    Runtime: "108 min",
    Genre: "Comedy, Drama, War",
    IMDB_Rating: 7.9,
    Overview:
      "A young boy in Hitler's army finds out his mother is hiding a Jewish girl in their home.",
    Meta_score: 58,
    Director: "Taika Waititi",
    Star1: "Roman Griffin Davis",
    Star2: "Thomasin McKenzie",
    Star3: "Scarlett Johansson",
    Star4: "Taika Waititi",
    No_of_Votes: 297918,
    Gross: "3,49,555",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BMGUyM2ZiZmUtMWY0OC00NTQ4LThkOGUtNjY2NjkzMDJiMWMwXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "The Irishman",
    Released_Year: 2019,
    Certificate: "R",
    Runtime: "209 min",
    Genre: "Biography, Crime, Drama",
    IMDB_Rating: 7.9,
    Overview:
      "An old man recalls his time painting houses for his friend, Jimmy Hoffa, through the 1950-70s.",
    Meta_score: 94,
    Director: "Martin Scorsese",
    Star1: "Robert De Niro",
    Star2: "Al Pacino",
    Star3: "Joe Pesci",
    Star4: "Harvey Keitel",
    No_of_Votes: 324720,
    Gross: "70,00,000",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BMTlkMmVmYjktYTc2NC00ZGZjLWEyOWUtMjc2MDMwMjQwOTA5XkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "The Gentlemen",
    Released_Year: 2019,
    Certificate: "A",
    Runtime: "113 min",
    Genre: "Action, Comedy, Crime",
    IMDB_Rating: 7.8,
    Overview:
      "An American expat tries to sell off his highly profitable marijuana empire in London, triggering plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
    Meta_score: 51,
    Director: "Guy Ritchie",
    Star1: "Matthew McConaughey",
    Star2: "Charlie Hunnam",
    Star3: "Michelle Dockery",
    Star4: "Jeremy Strong",
    No_of_Votes: 237392,
    Gross: "",
  },
  {
    Poster_Link:
      "https://m.media-amazon.com/images/M/MV5BNjcyYjg0M2ItMzMyZS00NmM1LTlhZDMtN2MxN2RhNWY4YTkwXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX67_CR0,0,67,98_AL_.jpg",
    Series_Title: "Sound of Metal",
    Released_Year: 2019,
    Certificate: "R",
    Runtime: "120 min",
    Genre: "Drama, Music",
    IMDB_Rating: 7.8,
    Overview:
      "A heavy-metal drummer's life is thrown into freefall when he begins to lose his hearing.",
    Meta_score: 81,
    Director: "Darius Marder",
    Star1: "Riz Ahmed",
    Star2: "Olivia Cooke",
    Star3: "Paul Raci",
    Star4: "Lauren Ridloff",
    No_of_Votes: 27187,
    Gross: "",
  }
];

export default Movies;
